name: GitHub Pages

on:
    push:
        branches:
        - deployment

jobs:
  permissions:
    pages: write
    contents: write
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./bin/update-gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOY_BRANCH: deployment
