name: Deploy

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Checkout gh-pages
      run: |    
        git checkout -b gh-pages
    - name: Commit new deployment
      run: |    
        sed s/--version--/$(git log -n 1 | head -n 1 | sed -e 's/^commit //' | head -c 8)/g prod/config.js > config.js
    - name: Commit new deployment
      run: |    
        git config --local user.email "diego@github"
        git config --local user.name "diego[bot]"
        git commit -a -m "Deployment $(date)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
